---
title: "Final Report for California and Louisiana"
author: "Asher Aley, Wendy Arenas, Ximena Juarez, Shadman Shahzahan"

output: openintro::lab_report
---

# Abstract

------------------------------------------------------------------


# Introduction
Every 10 years, electoral district boundaries are redrawn to reflect the constantly shifting and growing population and to ensure fair and equal representation. However, the new proposed redistricting plans may face legal challenges, forcing states to redraw their district boundaries mid-decade. Such was the case for the two states this report will be focusing on: California and Louisiana. 


# California Redistricting
In 2025, Texas’s new congressional map sought to add up to 5 Republican districts to help Trump and the Grand Old Party (GOP) in the midterm elections. To counteract these changes, California Governor Gavin Newsom proposed temporarily overriding the commission and creating districts more favorable to Democrats. In the end, voters approved California Proposition 50, a ballot measure that grants the state legislature the power to redraw California’s congressional map before the midterm, by 65% - 35%.

To better understand how redistricting could affect representation in California, our group analyzed voting and demographic data from the "2024 California L2 Voter File General Election Turnout Statistics Aggregated to 2020 Census Blocks", obtained from the Redistricting Data Hub. The data set contained information on voter registration and turnout by party affiliation, age, gender, and race. One of the most important aspects of the data that made it meaningful for our group was the 15-digit census block code named "GEOID20" because it allowed our team to join the voter data with census population data from the PL94171 package. This connection allowed us to incorporate population information when evaluating potential redistricting plans. This connection enabled us to incorporate population information when evaluating potential redistricting plans. 

During the data preparation process, we focused primarily on voter registration and turnout variables by age, gender, and party affiliation. While the dataset contained detailed racial categories, some were narrowly defined and represented relatively small populations. We also had access to broader demographic information through census data, and we chose to emphasize those larger population groups in our analysis.


We began with our analysis focused on one of California’s largest populations, the Hispanic population, making up 40%. Based on our findings, we’ve identified that areas in Northern rural California had denser Hispanic communities that voted for the Republican Party. Looking into why Trump received more support from the Hispanic community in the last election, it turned out that personal reasons influenced this change in party decision. One such example is how some families experienced positive changes during Trump’s previous term in office. 

As a result, Trump won the last election because of major support from the Hispanic community. If California wants to secure more democratic districts, areas with Hispanic Republican voters would need to be split, or they could be split from other areas and put into a safe Republican district. 

Another thing they would have to consider is the influence young voters could have on turnout.
Young voters have the potential to influence election results, but their lower voter turnout may keep counties Republican that might otherwise shift Democratic if youth participation were higher. It could be because most people assume California will be a blue state no matter what, and that their vote won’t matter; however, that kind of thinking could lead to trouble.


### Methods
The SMC method was used to randomly generate a large number of possible redistricting plans that met our criteria. The specific criteria we were using in the algorithm was population within each district could not vary by more than 1%, and the compactness had to be as close as possible to 1. However, there were no weights assigned to compactness, while there certainly could have been because it might take compactness as a suggestion versus priority. So, what the Sequential Monte Carlo simulation does is randomly create plans, by one precinct at a time, using a restraint of population within each district, not varying by more than 1%, and the precincts have no adjacency/contiguity issues. It runs the number of simulations that you specify, and the number of runs you would like as well, so if you want 100 simulations and 2 runs, it would be 200 proposed plans. The underlying process is that it creates a large number of “particles” like parts of the plan that will then be mixed with other particles to make a full plan (Kantas, 2009). The particles represent partial redistricting plans; the simulation starts in one area and grows from there into a full plan. The particles need to have no contiguity issues or other problems with the geometry that would disrupt the process of attaching precincts together for districts. When adding precincts to the starting one, it focuses on the population balance instruction and makes sure the district is formed when all the particles (developing maps) meet the criteria. Then it continues to the next area and repeats the process, until the number of districts wanted(specified) have been formed. If criteria are not met or constraints are violated, the simulation does another resample, and those bad particles get dropped, and the good ones are kept. If particles are dropped, it is because it surpasses the population balance constraint, which is a hard constraint. Compactness is more of a soft constraint, and so if the maps are very low compared to other randomized maps, the particles can be dropped. If there are more specified constraints or specific weights, then the process would drop the particles if they do not reflect the most important criteria. The overall idea is that SMC makes a random redistricting plan from scratch, versus starting from an existing plan and adjusting the precincts into different districts. Although it seems to be common that even with 1,000s of maps created, the maps tend to look very similar because the SMC does what it can with the data provided, and extreme cases or changes would require some data manipulation or running 100,000 more runs to find a very different plan, which would be unlikely to occur fairly. 

In a fun, simple way to grasp this information, think of playing a game of hide-and-seek with your eyes closed. Your friends are whistling from far away; your friends represent a proper map that meets the criteria you have specified. You try to move closer and can’t see your path, so you’re moving around, and then you hear other noises. Still, they are not your friends’ whistling, so that is not the right direction, and they have to be ignored. You are then moving closer to the proper path and staying in that area, while listening to the whistling get closer, and then finally you have found them. Then the process gets repeated with a new person, and the friends whistling are in a different area, and a new pathway is made, representing another plan. 

To find the Polsby-Popper ratio and Reock ratio for the compactness measure, the function of comp_polsby() and comp_reock() was used after the redist smc function to find the ratio for each district in each draw(map created), and then within each map created, found the average ratio for both Polsby and Reock, and arranged it highest to lowest in a different table/data frame to then find the best map in terms of compactness. Then, from there checked if that map was able to hit other aspects of fairness in terms of population, minority representation, and party affiliation behavior. The Polsby Popper measure is calculated by “taking the ratio of the area of the district to the area of the circle whose circumference matches the perimeter of the district,” and the Reock score is calculated by “taking the ratio of the area of the district to the area of the minimum circumscribing circle” (Redistricting, 2023). The Polsby score is very sensitive to jagged boundaries, so it will produce a lower score even if the shape of the district isn’t as irregular, but due to geographical characteristics of the state/boundaries, it can produce low Polsby scores.

### Results

# Adjacency Fix for California
California had 3 precincts that were disconnected from the others, and it were islands that were not connected to the mainland, so those were selected by their numbered row to be into a new data frame named bad precincts. Then, a function was made to add adjacency, to create a connection with one row to the next row, and one was subtracted from the adjacency list of those precincts that were disconnected to make them zero-indexed because the other contiguous precincts were zero-indexed as well. Then, the distances from the precinct to other precincts were computed, and the shortest nonzero distance to another precinct was found and saved. After, a connection between the input precinct and the closest to another precinct was added. This function was then used for every precinct found in the bad precinct data frame. These adjacencies were fixed and added back to the adjacency list to redistrict California. 

# California Extreme Gerrymander Map

In order to create a map that reached the political goals of California, which were to gain more democratic seats to counter Texas’s new republican redistricts, we had to break apart the state into sections. The 3 sections of California were the northern area, districts 1-22, Central California, districts 23-37, and Southern California, districts 38-53. This selection of districts was made by filtering existing districts from census data of California from 2020, and therefore using the geometries of those selected districts to remap new boundaries, still with population deviation of 1% and compactness in mind. With the northern part of California, 10 districts were mapped, Central had 19 remapped districts, and Southern California had 23 districts mapped, and the number of districts that we chose to create using the redist_map function were carefully chosen as they provided the most extreme gerrymandering results, where there were 0-3 republican districts, and the best map to represent the political agenda made 4 republican districts. Within each section, there were lots of groupings and summarizations that needed to be done to get the voting information as well, to know the strength of the favorable party in each district. This was taken by subtracting the total of the Democratic Party from the Republican and then dividing by the total, and then creating margin bins where if the percentage was in a certain range, then it would coincide with the text of that margin and be used with the color scale to portray a clear story and legend. Once the individual maps were made, their rows were combined into a new data frame and then mapped with the same scale and labels that had been used to have a full new proposed map of California with extreme gerrymandering. 

# Fair California Map

There is some packing because visually there is irregular, elongated shapes, and because in the last approved map from 2020 the number of majority minority districts was blank with over 60% minority group and now there is 23 districts with over 60% of the minority VAP and therefore suggest that packing was or was not done. There are in our current proposed map 3 districts withunder 30% of the minority VAP, in the 2020 California map there were blank so it mean there. 

The map created for California with the criteria of compactness as close as possible to 1, could only create 9-12 republican districts in 55,000 simulations. This may not help the agenda of reducing republican seats, but it is fairer in terms of compactness. The highest average Polsby-Popper score for a California map according to our simulation plans is .1968 and the highest average Reock score is .3978. Our team picked the map with the higher score of the two, which was the Reock Score. This map created 10 republican districts, and 36 majority minority districts, and only 5 of those were republican favoring. In terms of fairness, it gives representation to minority groups, it does its best in terms of compactness (Reock score), and it has the population balance, so that each district doesn’t vary by more than 1%. 
The map with higher Reock because it gave a more favorable compactness score, and no metric is the best one for compactness, and this map represented more acceptable fairness metrics. Also, the Reock score for the 2020 California map was averaged .341, so this new map is an improvement in terms of compactness because it is .0568 greater (16% increase). This calculation was made from determining the Reock score of each district of California in 2020 from the alarm data/census, and then the average of all of them combined. 

# Louisiana Redistricting
Louisiana’s congressional redistricting in the 2020s has so far been centered around racial gerrymandering. Louisiana’s 2020 congressional districts had 5 republican districts and 1 democratic district. However, to avoid being sued for diluting black voting power, Louisiana proposed a redistricting plan in 2022, because a third of Louisiana’s population is black. So, it had 4 republican districts and 2 democratic districts, with both democratic districts being majority minority. With the ruling of Louisiana v. Callais in 2026, Louisiana proposed a plan yet again due to racial gerrymandering, and this plan was passed into law. Louisiana’s new districts are similar to its 2020 districts. Both the 2020 and 2026 democratic districts pack black voters, diluting black voting power. These districts pack black voters by drawing lines around black neighborhoods in New Orleans and Baton Rouge. The 2022 proposed plan had a second majority-minority district span that was thin, but it also spanned over half of the state. This district also packed black neighborhoods, but it had to do so across the entire state.  

# Supreme Court case.  
Louisiana v. Callais was ruled on April 29th, 2026, and Louisiana’s 2022 proposed congressional districts were deemed to be unconstitutional due to racial gerrymandering. This ruling also impacted the integrity of the Voting Rights Act, as the Supreme Court found using predominantly race to redistrict to be a form of gerrymandering.  

This may have been the case in Louisiana, as the 2022 proposed map required packing that resulted in a thin  district that spanned over half the length of Louisiana. However, Louisiana’s one democratic district is not any better. The district, even in 2026, still packs black neighborhoods by splitting cities multiple cities apart. If redistricting plans cannot be decided by race, then Louisiana is still gerrymandering. 

### Methods
Because Louisiana has a history of drawing noncompact districts to control demographics, we decided to redistrict to do the opposite. Our first step in redistricting was to keep precincts within their parishes, and to group certain parishes together that shared the same cities (e.g. Caddo and Bossier parishes). Then, we generated 55,000 maps and picked the map with the highest average Reock compactness index across all districts. From that map, we moved precincts around for finetuning. The function we used prioritized preserving equal population across all districts, which causes district lines to cross parish borders, so we moved district lines to avoid crossing through parishes. District 6 required more manipulation. We initially wanted a second democratic district to reflect the third of the votes going toward the democratic, but this requires extreme gerrymandering. To compensate, we made District 6 a competitive district with republicans having the majority by 3.7%. District 6 includes the Baton Rouge area and other areas that allow its partisan lean to be within 5%. Finally, some district lines were moved to cross through parish borders, so that populations within each district would deviate by less than 1%. 

### Results
Roughly half of the registered voters are republican, and the other half are democrats. However, there are slightly more registered democrats than republicans, yet Louisiana is a very republican state. The two largest voter demographics in Louisiana in 2024 are white republicans with roughly 800,000 registered voters and black democrats with roughly 700,000 registered voters. However, the republican lean comes from voter turnout, in which 63% of black democrats voted compared to 81% of white republicans. Voter turnout can be significantly impacted by gerrymandering. If districts are drawn so that a certain favorable outcome is more guaranteed, then voters won’t feel like their vote matters.  

To be in alignment with the recent Supreme Court ruling, where race cannot be used as the predominant factor in remapping a state, maps are made randomly with no specific parameters or instructions to use race, and then analyze the voting age population percentage of the minority group in the newly made districts to see if they had their voting power diluted. The Hispanic and Black communities are the majority minority group in Louisiana. The fairest map for Louisiana had one majority minority district with 52% of the minority voting age population. The other districts contained a minority VAP of 47%, 42%, 35%, 33%, and 31%. This new map is an improvement of minority representation because the last map, according to alarm data, 2020 districts, had one district with 25% of the minority VAP, and one district with 67% of the minority VAP. According to Princeton research, if a new map has few districts with a percentage of minority VAP of 30%, then there is suspicion of underrepresentation, but our new map has now all districts above 30%, so the 2020 LA map was underrepresented using this method (Redistricting, 2021). Also, this new proposed map of ours has the majority minority district of 52% of the group versus the 2020 one with over 60%, which signaled overly packing. Therefore, in this simplified analysis of minority representation, the new proposed map meets minority representation criteria more fairly than before. The map from 2020 of Louisiana had a Reock score of .367, and the new one has a score of .4981, so about a 37% increase in compactness. So, this proposed map of ours demonstrates a fairer map compared to the 2020 map. 

## Goals and Attainment
California’s Proposition 50 favored only 4 republican districts' map. Our team reached a map that went against the agenda, with 10 republican districts, which is more than the old map from 2024 (9 republican districts), and we could not create a map with fewer than 4 republican districts. Although we did create a map with aggressive gerrymandering that resulted in 4 republican districts, which reached the agenda of California’s democratic party, so that goal was successfully met. Our fair map of California reaches two goals, which were to go against the political agenda in place by having +1 republican district (1 more than the 2020 California map), and it is more compact as well. While it has few competitive districts (0-5% margin wins), the lens we see it through is that communities that vote similarly are grouped in the non-competitive districts. So, less competitive districts can be good from that point of view. However, it would have been ideal if there were more competitive districts to have everyone’s vote make a difference.

Louisiana cannot, with voting data, have more than one democratic district without extreme gerrymandering, so that goal is not attainable. We made a map with one district, which is what they had to begin with. Another goal was to try not to dilute voting power for minorities, but based on geographical constraints, our plan only had one minority majority district, which is only 1/6 of the districts, when at least the Black demographic makes up 1/3 of the population in the state. Yet, it is due to the location of where the groups are that some are concentrated and others are dispersed. However, compared to the 2020 map from Louisiana, there is better minority representation because all the districts have at least 30% of the minority VAP. So, we did create a map that met the goal about not diluting minority votes from this approach of all districts at least at 30% or higher of the minority VAP, and there is an improvement of the packing because the majority minority district is not over 60% of the minority VAP but rather 52%, and compared to the 2020 map, it is an improvement as well. 

# Discussion
With Louisiana’s registered voters’ data, one can see there are more democratic registered voters than republican voters, but they are not the majority when it comes to elections, and this indicates that democrats are not voting. If democrats started to vote, they would make a difference, and then Louisiana might not be 5 republican districts, but 2 or 3 districts instead. A limitation of using this data to make maps was that it would assume 100% turnout rate, which is unlikely, and it makes an assumption that people vote the way they previously registered. We think there could be more campaigning in Louisiana to democrats that they can make a difference if they vote, and that their votes matter, and show them with visuals that they outnumber Republicans. Although with the political climate and state of the world affairs, there is no way of predicting how people will vote in the midterm elections. Our maps may be completely wrong or spot on when it comes to determining the party it favors. Our goals of wanting to make a fair map for both states were done to the best of our ability with hard measures, such as compactness and minority representations, but other factors, like competitiveness, were harder to attain. Although in a way competitiveness allows for fewer wasted votes, it shows that communities of interest were kept together if it is a safe district, and competitiveness favors more incumbents, so if someone doesn’t know who to vote for, they’ll vote for who was already in office and didn’t mess anything up in a non-competitive district. Versus in a competitive district, everyone knows their vote matters and that they can pick someone different, and it could change the outcome of things. 

# Source of Data  
According to Redistricting Datahub, they “[collect] data from trusted and official sources, checking the data for internal consistency and validating it against alternative datasets, soliciting feedback from stakeholders and users, and regularly auditing our processes to see what we can improve.” Therefore, we know the data we used from the redistricting hub is up to date, accurate, and of high quality, so it can be used in academic settings. 

# References 
Kantas, N., Doucet, A., Singh, S. S., & Maciejowski, J. M. (2009). An Overview of Sequential Monte Carlo Methods for Parameter Estimation in General State-Space Models. IFAC Proceedings Volumes, 42(10), 774–785. https://doi.org/10.3182/20090706-3-fr-2004.00129 

Redistricting Report Card Methodology. (2023). Gerrymander.princeton.edu. https://gerrymander.princeton.edu/redistricting-report-card-methodology
...

